import "./globals.css";
import localFont from 'next/font/local'
import BG from "Media/Body/bg.jpg";
import { Poppins } from 'next/font/google'
import Image from "next/image";

const poppins = Poppins({
  weight: ['400', '600'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
})

const Francy = localFont({
  src: "./fonts/CookConthic.woff",
  display: 'swap',
  variable: '--font-Francy',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Francy.variable} ${poppins.variable} relative `}>
        <Image src={BG} fill={true} className="object-fill -z-10 absolute" alt="Faisal Qadeer Yousufi" />
        {children}
      </body>
    </html>
  );
}
